const CLICK_CELL = 'CLICK_CELL';
const CELL_PRESSED = 'CELL_PRESSED';
const CHANGE_THEME = 'CHANGE_THEME';
const CHANGE_LOG_DIR = 'CHANGE_LOG_DIR';
const MOVE_TO_STEP = 'MOVE_TO_STEP';
const SET_ALLOW_MODAL = 'SET_ALLOW_MODAL';

export {
    CLICK_CELL, 
    CELL_PRESSED,
    CHANGE_THEME, 
    CHANGE_LOG_DIR, 
    MOVE_TO_STEP, 
    SET_ALLOW_MODAL
};
